export const PUSH_ITEM_TO_CART = "PUSH_ITEM_TO_CART"
export const DELETE_ITEM_IN_CART = "DELETE_ITEM_IN_CART"
export const DELETE_ALL_ITEM_IN_CART = "DELETE_ALL_ITEM_IN_CART"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"

export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"

export const SET_CURRENT_USER = "SET_CURRENT_USER"
