export const productsList = [
  {
    id: "p1",
    name: "Táo Lào Cai",
    type: "fruit",
    src: "/images/apple.jpg",
    price: 500000,
    discount: 0,
    remains: 0,
  },
  {
    id: "p2",
    name: "Bắp cải",
    type: "vegetable",
    src: "/images/bapCaiHd.jpg",
    price: 500000,
    discount: 0,
    remains: 0,
  },
  {
    id: "p3",
    name: "Bắp cải tím",
    type: "vegetable",
    src: "/images/bapCaiTim.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p4",
    name: "Bí đỏ",
    type: "vegetable",
    src: "/images/biDo.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p6",
    name: "Bí đỏ dài Đà Nẵng",
    type: "vegetable",
    src: "/images/biDoDai.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p7",
    name: "Bưởi da xanh",
    type: "fruit",
    src: "/images/buoi.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p8",
    name: "Cà chua",
    type: "vegetable",
    src: "/images/caChua.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p9",
    name: "Cải cúc",
    type: "vegetable",
    src: "/images/caiCuc.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p10",
    name: "Cải ngồng",
    type: "vegetable",
    src: "/images/caiNgong.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p11",
    name: "Cải xanh",
    type: "vegetable",
    src: "/images/caiXanh.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p12",
    name: "Cam Hà Giang",
    type: "fruit",
    src: "/images/camHaGiang.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p13",
    name: "Cam mỹ",
    type: "fruit",
    src: "/images/camMy.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "pp1",
    name: "Cam sành",
    type: "fruit",
    src: "/images/camSanh.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p15",
    name: "Cam vàng Úc",
    type: "fruit",
    src: "/images/camVangUc.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p16",
    name: "Cần tây",
    type: "vegetable",
    src: "/images/canTay.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p17",
    name: "Cà tím",
    type: "vegetable",
    src: "/images/caTim.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p18",
    name: "Chanh leo",
    type: "fruit",
    src: "/images/chanhLeo.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p19",
    name: "Chuối tây",
    type: "fruit",
    src: "/images/chuoi.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p20",
    name: "Chuối tiêu",
    type: "fruit",
    src: "/images/chuoiCao.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p21",
    name: "Chuối xanh",
    type: "fruit",
    src: "/images/chuoiXanh.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p22",
    name: "Củ đậu",
    type: "fruit",
    src: "/images/cuDau.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p23",
    name: "Đậu Cove",
    type: "vegetable",
    src: "/images/dauCove.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p24",
    name: "Dưa chuột",
    type: "fruit",
    src: "/images/duaChuot.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p25",
    name: "Dưa hấu",
    type: "fruit",
    src: "/images/duaHau.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p26",
    name: "Dưa lê",
    type: "fruit",
    src: "/images/duaLe.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p27",
    name: "Dứa thơm",
    type: "fruit",
    src: "/images/duaThom.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p28",
    name: "Dừa Bến Tre",
    type: "fruit",
    src: "/images/duaXiem.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p29",
    name: "Đu đủ",
    type: "vegetable",
    src: "/images/dudu.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p30",
    name: "Gừng củ",
    type: "vegetable",
    src: "/images/gungCu.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p31",
    name: "Hành củ Hải Dương",
    type: "vegetable",
    src: "/images/hanhCuHD.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p32",
    name: "Hành tây",
    type: "vegetable",
    src: "/images/hanhTay.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p33",
    name: "Hạt sen",
    type: "vegetable",
    src: "/images/hatSen.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p34",
    name: "Khoai lang",
    type: "vegetable",
    src: "/images/khoaiLang.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p35",
    name: "Lê Hưng Yên",
    type: "fruit",
    src: "/images/leHanQuoc.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p36",
    name: "Rau mùng tơi",
    type: "vegetable",
    src: "/images/mongToi.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p37",
    name: "Mướp đắng",
    type: "vegetable",
    src: "/images/muopDang.jpg",
    price: 500000,
    discount: 5,
    remains: 0,
  },
  {
    id: "p38",
    name: "Ngô",
    type: "vegetable",
    src: "/images/ngo.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p39",
    name: "Ổi Thanh Hà",
    type: "fruit",
    src: "/images/oiThanhHa.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p40",
    name: "Ớt chuông",
    type: "vegetable",
    src: "/images/otChuong.jpg",
    price: 500000,
    discount: 5,
    remains: 0,
  },
  {
    id: "p41",
    name: "Ớt ngọt đỏ",
    type: "vegetable",
    src: "/images/otMau.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p42",
    name: "Ớt đà lạt",
    type: "vegetable",
    src: "/images/otNgot.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p43",
    name: "Ớt cay",
    type: "vegetable",
    src: "/images/otNho.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p44",
    name: "Bầu loại to",
    type: "vegetable",
    src: "/images/quaBau.jpg",
    price: 500000,
    discount: 5,
    remains: 0,
  },
  {
    id: "p45",
    name: "Rau mầm xanh",
    type: "vegetable",
    src: "/images/rauMamXanh.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p46",
    name: "Rau dền đỏ",
    type: "vegetable",
    src: "/images/rauDen.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p47",
    name: "Rang lang",
    type: "vegetable",
    src: "/images/rauLang.jpg",
    price: 500000,
    discount: 5,
    remains: 0,
  },
  {
    id: "p48",
    name: "Rau muống",
    type: "vegetable",
    src: "/images/rauMuong.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p49",
    name: "Rau ngót",
    type: "vegetable",
    src: "/images/rauNgot.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p50",
    name: "Roi nha trang",
    type: "fruit",
    src: "/images/roi.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p51",
    name: "Su hào Hải Dương",
    type: "vegetable",
    src: "/images/suhao.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p52",
    name: "Táo Hưng Yên",
    type: "fruit",
    src: "/images/taoNewZelan.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p53",
    name: "Táo Quảng Nam",
    type: "fruit",
    src: "/images/taoNgon.jpg",
    price: 500000,
    discount: 5,
    remains: 0,
  },
  {
    id: "p54",
    name: "Táo Đà Lạt",
    type: "fruit",
    src: "/images/taoPhap.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p55",
    name: "Thanh long Kiên Giang",
    type: "fruit",
    src: "/images/thanhLong.jpg",
    price: 500000,
    discount: 5,
    remains: 0,
  },
  {
    id: "p56",
    name: "Tỏi củ Hải Dương",
    type: "vegetable",
    src: "/images/toiCu.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p57",
    name: "Xoài Nghệ An",
    type: "fruit",
    src: "/images/xoai.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p58",
    name: "Xoài ngọt Thái Bình",
    type: "fruit",
    src: "/images/xoaiCat.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p59",
    name: "Xoài xanh",
    type: "fruit",
    src: "/images/xoaiThai.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p60",
    name: "Xoài Nam Đinh",
    type: "fruit",
    src: "/images/xoaiTuQuy.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p61",
    name: "Xoài chín Phú Thọ",
    type: "fruit",
    src: "/images/xoaiVangUc.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p62",
    name: "Gạo tẻ",
    type: "rice",
    src: "/images/gao.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p63",
    name: "Gạo tẻ An Giang",
    type: "rice",
    src: "/images/gaoAnGiang.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p64",
    name: "Gạo bắc thơm",
    type: "rice",
    src: "/images/gaoBacThom.jpg",
    price: 500000,
    discount: 5,
    remains: 0,
  },
  {
    id: "p65",
    name: "Gạo Ba Vì",
    type: "rice",
    src: "/images/gaoBaVi.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p66",
    name: "Gạo Hải Phòng",
    type: "rice",
    src: "/images/gaoHaiPhong.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "7257cb36-b4fa-42af-b338-7a94b66049f4",
    name: "Gạo lứt",
    type: "rice",
    src: "/images/gaoLut.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "33068280-7ad3-4532-8bc3-b33b8478c732",
    name: "Gạo Nam Định",
    type: "rice",
    src: "/images/gaoNamDinh.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "4e9edc19-c814-4279-8d8d-832009ab6b49",
    name: "Gạo nếp cái hoa vàng",
    type: "rice",
    src: "/images/gaoNepCaiHoaVang.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "2b722451-7002-4f72-8a19-e5de71a9c7c2",
    name: "Gạo ST25 Việt Nam",
    type: "rice",
    src: "/images/gaoST25.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p14",
    name: "Gạo Thái Bình",
    type: "rice",
    src: "/images/gaoThaiBinh.jpg",
    price: 500000,
    discount: 5,
    remains: 5000,
  },
  {
    id: "p5",
    name: "Gạo Thái Nguyên",
    type: "rice",
    src: "/images/gaoThaiLan.jpg",
    price: 500000,
    discount: 5,
    remains: 0,
  },
]
